development:
  adapter: postgresql
  encoding: utf8
  database: proto_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: proto_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: proto_production
  host: localhost
  pool: 5
